"""clean final schema

Revision ID: 70c7378c7cbe
Revises: 
Create Date: 2025-05-24 04:22:01.180189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70c7378c7cbe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING_VERIFICATION', 'VERIFIED', 'VERIFICATION_FAILED', 'BLOCKED', 'REGISTERED', name='user_status_enum'), nullable=False),
    sa.Column('phoneNumber', sa.String(), nullable=True),
    sa.Column('identifierType', sa.Enum('NIN', 'NHS', name='identifier_type_enum'), nullable=True),
    sa.Column('identifierValue', sa.String(), nullable=True),
    sa.Column('auth_provider', sa.Enum('EMAIL', name='auth_provider_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_auth_provider'), 'users', ['auth_provider'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_identifierType'), 'users', ['identifierType'], unique=False)
    op.create_index(op.f('ix_users_identifierValue'), 'users', ['identifierValue'], unique=False)
    op.create_index(op.f('ix_users_phoneNumber'), 'users', ['phoneNumber'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_phoneNumber'), table_name='users')
    op.drop_index(op.f('ix_users_identifierValue'), table_name='users')
    op.drop_index(op.f('ix_users_identifierType'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_auth_provider'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
