"""add phone_number to users

Revision ID: 2f8ba79c8a9e
Revises: c71bb0786f7d
Create Date: 2025-05-11 22:12:59.889856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f8ba79c8a9e'
down_revision: Union[str, None] = 'c71bb0786f7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_phoneNumber'), 'users', ['phoneNumber'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phoneNumber'), table_name='users')
    # ### end Alembic commands ###
